### ISSUE TITLE
add user clothes

### ISSUE THREAD

**Issue by gvarados1** [mzegar/sbox-TTT#25]
add clothes to the players. It's really hard to figure out who to shoot when everyone is a naked sausage

**Comment by mzegar** [comment]
Here are the two things kinda blocking this.

1. Every single player needs to have the same exact clothes as was in vanilla TTT (except detectives)
2. We need some more interesting clothes than what FP currently provides

If we could get some interesting-looking clothes for the game mode, I'm down to add this.

**Comment by gvarados1** [comment]
or you can just put on a random outfit every round

**Comment by mzegar** [comment]
So in the vanilla versions of TTT every single player had the exact same clothing on. This was because clothing shouldn't be the only determining factor on whether or not to kill someone.

Some later GMOD servers went crazy and started doing custom player models for each player etc. etc. My issue with this is it allows players to potentially kill another player due to a clothing item they potentially saw previously.

I'm toying with the idea of throwing it behind a tickbox in the server settings, but I'm honestly not sure if I even want players to experience the game like this.

Let me know if that makes sense.

**Comment by Fires1** [comment]
I'd vote for a tickbox just purely on allowing host customization of the factor. I am not a fan of random clothing, or unique clothing. I think it adds some bullshit to the way TTT is played. "KOS black haired anime girl", as opposed to getting names.

**Comment by mzegar** [comment]
Tickbox may be the way to go, this would require additional work in modifying how the `disguiser` works as well, since it currently blocks out your name. If clothing is unique on a per-player basis, the perk becomes completely useless.

I'm going to leave this open and think about throwing it behind a tickbox a server owner can change.

**Comment by Fires1** [comment]
> If clothing is unique on a per-player basis, the perk becomes completely useless.

I think this has always been a problem, I think people just don't care because most people never used the disguiser anyways. I think it's worth looking into later, or at the very least adding a small amount of placeholder clothes so it isn't totally naked.

**Comment by gvarados1** [comment]
disguiser should change outfit too. that's how disguises work irl.

**Comment by gvarados1** [comment]
Now that I'm thinking about it... I really like this. It would add another layer of depth to the game.
Randomized outfits at the start of each round and the traitors can change outfits with the disguiser.

All the outfits would be pretty similar looking, maybe just like 2-3 different outfits. Enough that you can track individuals in a crowd but can't really call them out by their looks. Currently everyone meshes together in a crowd and you can't figure out who to shoot.

**Comment by brogrammer777** [comment]
It could work if there is later support for non terry models and non in-game outfit system

**Comment by gvarados1** [comment]
> It could work if there is later support for non terry models and non in-game outfit system

you can code literally anything you want in s&box. This is a game engine, not gmod.

**Comment by youarereadingthis** [comment]
The game "The Ship" supports custom cosmetics if I remember right, and has a similar scheme to TTT. Game supports cosmetics by default already. It's a fun idea but I don't like that in TTT for reasons already talked about here.

If you're going to optionally support various outfits(PLEASE don't by default) then I strongly suggest having the disguiser support copying someone's outfit but always hiding your name. Then it would be fair if you're smart, and not inherently undermine the mystery element that makes the game so fun.

Detectives should be able to dress themselves up to their hearts content, though.

**Comment by Fires1** [comment]
If you wanted to modernize the disguiser, instead of hiding the name plate, you could just copy the outfit and nameplate of a person. Might be difficult to balance though.

**Comment by youarereadingthis** [comment]
I have hear about but not seen in practice a Name Tag ripping feature where you can do that.
Would be interesting as a separate equipment/feature idea.

**Comment by brogrammer777** [comment]
> If you wanted to modernize the disguiser, instead of hiding the name plate, you could just copy the outfit and nameplate of a person. Might be difficult to balance though.

Disguiser never stole someone's name. It just made your name invisible if someone looked at you.

**Comment by mzegar** [comment]
I'm not going to have a server tick for this. I'm completely removing the idea of people modifying the gameplay themselves through server settings. I don't trust people with figuring out the game rules themselves and I want a unified experience across anyone that plays the base game mode. If anyone doesn't like it, they can make an "addon" or whatever incarnation s&box comes up with.

"s&box community" is working on some player models, we may be able to switch to them whenever they are out. If we do switch to these models, every single outfit will be the same except the detective. I'm not doing different outfits since that doesn't fit how I want the gameplay to occur, and doesn't respect the vanilla TTT gamemode.

**Comment by mzegar** [comment]
Added clothes since FP added some. Thanks for this post.
