### ISSUE TITLE
Advanced Shop Menu

### ISSUE THREAD

**Issue by mzegar** [mzegar/sbox-TTT#3]
https://cdn.discordapp.com/attachments/834694052875730954/930321937119449099/steamuserimages-a.akamaihd.jpg

**Comment by youarereadingthis** [comment]
While the features here look like improvements, personally I think the equipment menu would be better with a spreadsheet-like list of equipment that you can click on for more detail instead of big ol buttons.

You can still see silkicon-like icons(such as literal silkicons) leftmost of each row, and "Category", "Stock", "Cost" columns for each row.

**Comment by mzegar** [comment]
I'm closing this in favour of the other thread.
