### ISSUE TITLE
Licence issues

### ISSUE THREAD

**Issue by Alf21** [mzegar/sbox-TTT#54]
This project is based on [TTT Reborn](https://github.com/TTTReborn/tttreborn), which uses the same license: <https://github.com/TTTReborn/tttreborn/blob/master/LICENSE>.

Since you have hard-copied the entire project rather than forking it, you will need to do additional work to comply:
- Copyright notice
- Indicate changes
- Disclosure of source

Personally, I am very disappointed by your behavior of not even listing anyone from the old team here <https://github.com/mzegar/sbox-TTT#credits> but talking badly about disagreements in the group and extensibility (while still using most of the extensible systems).
Because you cut all ties with the old team, I have to handle it that way, officially.

**Comment by mzegar** [comment]
Hey, feel free to message me directly about this as well, or we can continue the chat here. 

We've recently completely rewritten the game mode from the ground up. You'll notice all parts of the codebase are no longer here (ex. Translations, shops, visual scripting, etc.). I've gone ahead and purged all previous GitHub commits to avoid any infringing.

If you think any part of our repo is infringing, please feel free to let me know and I'd be happy to resolve it.

Thanks,

**Comment by Alf21** [comment]
Thank you for your reply and the goal to solve the problem :)

Via git diff, I found lot of exact code in:
- UI, e.g. GameTimer, Chat, InfoFeed, HUD ...
- In-Game UI stuff like InventorySelection, NamePlate, PlayerInfo, ...
- Internal stuff like Rounds, PlayerRole, PlayerDamage, PlayerAFK, Cameras
- Map entity stuff like LogicButtons, ...
- Items like health station, radar, ...

It's not a completed list and a lot of same code is "complex" or custom one.
A fork had avoided any infringing and additional work, but I understand that decision if your goal have been to rebuild from the ground (even that I don't understand why getting to this decision).

Thanks and all the best as well.

**Comment by mzegar** [comment]
I'm a bit upset that you are going to the length of claiming that Facepunch's "Hidden" round code is your own entity. It's not. It's also a bit upsetting knowing that I assisted your entire team with getting keys for s&box, and you are here attempting to claim Facepunch's "Hidden" round code is your property. 

Here is a quick list I generated in a few mins about some of your points...
- [The round system was implemented by me, initially taken from Hidden, you cannot really claim that as your "own" code](https://github.com/TTTReborn/tttreborn/commit/bc927fd62e8afd6db0e8de8a9ee3d286bc7c70de)
- [Player roles are completely new, I think I might have actually written the original ones, but we are using an asset system for them now.](https://github.com/mzegar/sbox-TTT/blob/main/code/roles/BaseRole.cs)
- PlayerAFK was not written by any Reborn members, it was written by GravityWolf, and reviewed by me. GravityWolf was actually extremely happy that I kept his PlayerAFK system for this gamemode.
- [Camera logic was written by me, but again, referenced from Facepunch's code](https://github.com/TTTReborn/tttreborn/commit/acba3dabc3e3ebbe0197ed57f85f3bb76fce0aa0)
- All Hammer logic was written by Fires, who has contributed to this repository. He has no issues with us using the code (it's also been modified since)
- [All items have been completely reworked (i.e Healthstation), as you can see we actually use an asset system now.](https://github.com/mzegar/sbox-TTT/blob/main/code/items/equipments/HealthStation.cs#L1-L19)
- Every in-game UI has gone through refactors (InventorySelection which I wrote originally, Fires who wrote NamePlate, etc.)

What is even worse, is I've realized that you've legitimately already copied from our repo (I personally don't care since it's open-source).
(for longer context https://github.com/TTTReborn/tttreborn/commit/97eba6d75a010443b363d920b326f0c3a1835762)
```csharp
/// <summary>
/// Spawn weapons of a specific category.
/// </summary>
[Property(Title = "Spawn weapons of a specific category")]
public CarriableCategories? Category { get; set; } = null;
```

And here is code I committed a few days ago...
https://github.com/mzegar/sbox-TTT/blob/main/code/items/weapons/WeaponRandom.cs
```csharp
[Property( "Ammo Type to Spawn", "If changed, will only spawn weapons of the selected ammo type." )]
public AmmoType SelectedAmmoType { get; set; } = AmmoType.None;
```

I only included a small snippet of code (you can see the full code changes in the links above), but, you took the exact approach of being able to spawn in weapons based on their "Hold/Ammo" type, literally a few days after.

I was originally trying to be as helpful as possible to resolve this, but the blatant attempts to pass ideas such as a Round system as your own, plus the blatant plagiarism of my own repo... (even though I don't care about this, only mentioning since you do). 

I'm closing this issue since I don't think you actually care about resolving this. All I'm trying to do is make an open-source TTT game for the community. I highest suggest you take the Reborn team as well and strive to do the same.

Best of luck,

- Matt

![image](https://user-images.githubusercontent.com/32153021/155903278-fb56ee74-bdd0-49f0-8f65-1cb8be064026.png)

**Comment by Alf21** [comment]
The code was released in a project under it's license. I never claimed it my own entity, as it's a community project anyways. There is a reason for credits and why GitHub has a "Fork" feature - to keep things simple. That had avoided this issue, but anyways, I gonna try to answer your points as far as I can. Please keep in mind this is regarding the license all of us agreed on, and this is to preserve community contributions and honor their work. Regarding the keys: I don't think it is reasonable to justify the hard copying with other facts. Anyways, I think every of our team thanked you and I think you learned something working in our team, or at least together with me, as well like I did....

1. Round-System: Please use Git Blame before taking such statements. Even if it was initially created, regarding the license, changes are included: Here is a [Link](https://github.com/TTTReborn/tttreborn/blame/master/code/gamemode/Game.cs)
2. Role-System: I don't wanna go into detail as I already said, git diff is showing lot's of same code. But as an example: [TTT Reborn](https://github.com/TTTReborn/tttreborn/blame/master/code/roles/TraitorRole.cs) vs "[TTT](https://github.com/mzegar/sbox-TTT/blob/main/code/roles/TraitorRole.cs)"
3.  "PlayerAFK was not written by any Reborn members, it was written by GravityWolf, and reviewed by me. GravityWolf was actually extremely happy that I kept his PlayerAFK system for this gamemode" => Okay, I didn't heard anything about that, but if it's right, then this is no issue. Anyways, reviewed by "us" ;)
4. Camera-System: Just a snippet, a detailed treatment of the issue would be an advantage: [FirstPersonCamera](https://github.com/TTTReborn/tttreborn/blame/master/code/player/camera/FirstPersonSpectatorCamera.cs), [etc](https://github.com/TTTReborn/tttreborn/blob/master/code/player/camera/IObservationCamera.cs).
5. Hammer entities: [Just an example](https://github.com/TTTReborn/tttreborn/blame/master/code/map/logicbutton/TTTLogicButton.cs). Btw. I don't have an issue if you're using our code, we are just talking about credits and the corresponding license. It's no restriction.
6. Items: That's wrong: [Radar](https://github.com/TTTReborn/tttreborn/blame/master/code/items/perks/radar/Radar.cs) (As I already listed)
7. UI: "refactors" indicates changed original code. I don't have to go into detail here.

Regarding your accusation that I've copied your code: Please show a snippet, because your snippet has no similarities, even that I COMBINED the already existing Slot-System with the already existing Ammo-System like we had done it in TTT2 ;)
Anyways, I can't see any commit that was prior mine in this repo here,...
If we are talking about copying, maybe I can point to the exact changes I did after the Pain Day II that appeared in your repo, but I don't care as there wasn't a lot of other changes possible, but amazing that we are using the same naming and repositioning.

Regarding "I'm closing this issue since I don't think you actually care about resolving this", I can say, that's what should be called "blatant" here.

Sad that we aren't working on one side anymore as I can say it's confusing for everyone to have multiple TTT projects, but that have been your decision.
That said, I thank you very much as well as for your wise advice. We wanna do so, we'll give our best depending on the available freetime :)

Oh and sorry for the late answer, as I can just work on the project on weekends, I couldn't answer faster.

Kind regards,
Alf21

Original Message:
![image](https://user-images.githubusercontent.com/11843790/156853527-5a2a8e08-ebde-4ad4-bdac-310c28e7bea8.png)
